# Generated by Django 4.2.16 on 2024-12-28 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Posts", "0003_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
    ]
